### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by gaby** [100security/magika-dashboard#1]
@100security Can you add an MIT and/or Apache 2.0 License file to this repo? Without that it's imposibe to make changes to this dashbaord or forks.

Awesome work! Thanks!

**Comment by 100security** [comment]
@gaby Thank you, I already added the license file to the repo!

**Comment by gaby** [comment]
> @gaby Thank you, I already added the license file to the repo!

Thank you! 💪 If i come up with anything will submit a PR :-)
